version: '3'

services:
  # NATS Server
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream", "--http_port=8222"]
    networks:
      - mcp-network

  # Example MCP NATS application
  mcp-nats:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    command: python docker-example.py
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge